In [1]:
r"""
指定一步转移概率和初始状态
得到马尔科夫链每一步的状态
"""

'\n指定一步转移概率和初始状态\n得到马尔科夫链每一步的状态\n'

In [2]:
import numpy as np

In [3]:
P = np.matrix([
    [0.65, 0.28, 0.07],
    [0.15, 0.67, 0.18],
    [0.12, 0.36, 0.52]
])

In [4]:
pi0 = np.matrix([0.7, 0.2, 0.1])

In [5]:
pi = pi0
for _ in range(30):
    print(pi)
    pi = np.matmul(pi, P)

[[0.7 0.2 0.1]]
[[0.497 0.366 0.137]]
[[0.39439 0.4337  0.17191]]
[[0.3420377 0.4628958 0.1950665]]
[[0.31516686 0.47613468 0.20869846]]
[[0.30132247 0.4823884  0.21628912]]
[[0.29417256 0.48543461 0.22039283]]
[[0.2904745  0.48695092 0.22257458]]
[[0.28856001 0.48771683 0.22372316]]
[[0.28756831 0.48810742 0.22432427]]
[[0.28705443 0.48830783 0.22463774]]
[[0.28678808 0.48841107 0.22480084]]
[[0.28665002 0.48846439 0.2248856 ]]
[[0.28657844 0.48849196 0.2249296 ]]
[[0.28654133 0.48850623 0.22495244]]
[[0.28652209 0.48851363 0.22496428]]
[[0.28651212 0.48851746 0.22497043]]
[[0.28650695 0.48851944 0.22497361]]
[[0.28650426 0.48852047 0.22497526]]
[[0.28650287 0.488521   0.22497612]]
[[0.28650215 0.48852128 0.22497656]]
[[0.28650178 0.48852142 0.2249768 ]]
[[0.28650159 0.4885215  0.22497691]]
[[0.28650149 0.48852154 0.22497698]]
[[0.28650143 0.48852156 0.22497701]]
[[0.28650141 0.48852157 0.22497703]]
[[0.28650139 0.48852157 0.22497703]]
[[0.28650139 0.48852158 0.22497704]]
[[0.28650138

In [6]:
pi0 = np.matrix([0.17, 0.23, 0.6])

In [7]:
pi = pi0
for _ in range(30):
    print(pi)
    pi = np.matmul(pi, P)

[[0.17 0.23 0.6 ]]
[[0.217  0.4177 0.3653]]
[[0.247541 0.472127 0.280332]]
[[0.26536054 0.48655609 0.24808337]]
[[0.27523777 0.48960354 0.23515869]]
[[0.28056412 0.48975808 0.2296778 ]]
[[0.28339173 0.48937987 0.2272284 ]]
[[0.28487901 0.48903642 0.22608457]]
[[0.28565697 0.48881097 0.22553206]]
[[0.28606252 0.48867884 0.22525863]]
[[0.2862735  0.48860544 0.22512106]]
[[0.28638312 0.48856581 0.22505107]]
[[0.28644003 0.48854475 0.22501522]]
[[0.28646956 0.48853367 0.22499677]]
[[0.28648488 0.48852787 0.22498725]]
[[0.28649282 0.48852485 0.22498233]]
[[0.28649694 0.48852328 0.22497978]]
[[0.28649908 0.48852246 0.22497846]]
[[0.28650018 0.48852204 0.22497778]]
[[0.28650076 0.48852182 0.22497742]]
[[0.28650106 0.4885217  0.22497724]]
[[0.28650121 0.48852164 0.22497715]]
[[0.28650129 0.48852161 0.2249771 ]]
[[0.28650133 0.4885216  0.22497707]]
[[0.28650135 0.48852159 0.22497706]]
[[0.28650137 0.48852158 0.22497705]]
[[0.28650137 0.48852158 0.22497705]]
[[0.28650137 0.48852158 0.22497705]]


it can be pagerank

In [8]:
pi = P
for _ in range(30):
    print(pi)
    pi = np.matmul(pi, P)

[[0.65 0.28 0.07]
 [0.15 0.67 0.18]
 [0.12 0.36 0.52]]
[[0.4729 0.3948 0.1323]
 [0.2196 0.5557 0.2247]
 [0.1944 0.462  0.3436]]
[[0.382481 0.444556 0.172963]
 [0.253059 0.514699 0.232242]
 [0.236892 0.487668 0.27544 ]]
[[0.33605161 0.46721388 0.19673451]
 [0.26956224 0.49931197 0.23112579]
 [0.2601828  0.49222572 0.24759148]]
[[0.31212377 0.47795217 0.20992406]
 [0.27784735 0.49322173 0.22893092]
 [0.27266366 0.49177535 0.235561  ]]
[[0.29976416 0.48319527 0.21704056]
 [0.28205575 0.49067095 0.22727331]
 [0.279265   0.49063727 0.23009774]]
[[0.29337086 0.4858094  0.22081973]
 [0.28420967 0.48954353 0.22624679]
 [0.28272957 0.48975635 0.22751408]]
[[0.29006084 0.48713125 0.22280791]
 [0.28531743 0.48902172 0.22566085]
 [0.28453936 0.4892061  0.22625454]]
[[0.28834618 0.48780582 0.223848  ]
 [0.28588889 0.48877134 0.22533977]
 [0.28548204 0.48889074 0.22562721]]
[[0.28745765 0.48815211 0.22439024]
 [0.28618425 0.488648   0.22516774]
 [0.28597221 0.48871757 0.22531023]]
[[0.28699712 0.488